# Site settings
title: Coding Club UC3M
email: codingDOTclubDOTuc3mATgmailDOTcom
description: > # This means to ignore newlines until "baseurl:"
  A series of participative sessions among coding enthusiasts interested
  in data analysis, number crunching and teaching of statistics. Quite R-based
  but welcoming other languages and tools.
url: "https://codingclubuc3m.github.io" # The base hostname & protocol for your site
github_username: codingclubuc3m
permalink: /:year-:month-:day-:title.html
author: Coding Club UC3M
baseurl: "https://codingclubuc3m.github.io/"
url: 'https://codingclubuc3m.github.io/'

# Limit posts on Home page to this number
homepostlimit: 10

# Display future posts
future: true

# Disqus comments:
disqus: true
shortname: codingclubuc3m

# Social media buttons
twitter: true # Add a twitter button to each post
facebook: true # Add a facebook share button to each post

# Build settings

# Rendering engine
markdown: kramdown

author:
  name: 'Coding Club UC3M'
  url: https://codingclubuc3m.github.io

github:
  repo: https://github.com/codingclubuc3m/codingclubuc3m.github.io

include:
  - public
