# Site settings
title: Coding Club UC3M
email: codingDOTclubDOTuc3mATgmailDOTcom
description: > # this means to ignore newlines until "baseurl:"
  A blog devoted mostly to the teaching of undergraduate-level statstics
  and data analysis with R, along with occasional technical notes on R-related
  tools.
url: "https://codingclubuc3m.github.io" # the base hostname & protocol for your site
github_username: codingclubuc3m
permalink: /:year/:month/:day/:title.html
# highlighter:  rouge (on my Mac, need to set this to rouge or flas with Jekyll 3.0)
author: Coding Club UC3M

baseurl: "/" # the sub-path of your proejct site, e.g. /myProject/
             # or "/" for user site

# limit posts on Home page to this number:
homepostlimit:  4

# Disqus comments:
disqus:           true
shortname:        codingclubuc3m

# Social Media
twitter:          true # add a twitter button to each post
facebook:         true # add a facebook share button to each post

# Build settings

# rendering engine
markdown: kramdown

author:
  name:           'Coding Club UC3M'
  url:            https://codingclubuc3m.github.io

github:
  repo:           https://github.com/codingclubuc3m/codingclubuc3m.github.io
